(function() {var implementors = {};
implementors['plaid'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>StdError</a> for <a class='enum' href='plaid/api/error/enum.Error.html' title='plaid::api::error::Error'>Error</a>",];implementors['plaid'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>StdError</a> for <a class='enum' href='plaid/api/error/enum.Error.html' title='plaid::api::error::Error'>Error</a>",];implementors['plaid'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>StdError</a> for <a class='enum' href='plaid/api/error/enum.Error.html' title='plaid::api::error::Error'>Error</a>",];implementors['plaid'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>StdError</a> for <a class='enum' href='plaid/api/error/enum.Error.html' title='plaid::api::error::Error'>Error</a>",];implementors['plaid'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>StdError</a> for <a class='enum' href='plaid/api/error/enum.Error.html' title='plaid::api::error::Error'>Error</a>",];implementors['plaid'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>StdError</a> for <a class='enum' href='plaid/api/error/enum.Error.html' title='plaid::api::error::Error'>Error</a>",];implementors['plaid'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>StdError</a> for <a class='enum' href='plaid/api/error/enum.Error.html' title='plaid::api::error::Error'>Error</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
